name: Semantic Release
run-name: ${{ github.actor }} is (maybe) creating new version  🚀
## This workflow is triggered by the completion of the Check Frontend Sanity and Check Backend Sanity workflows and runs only on the main branch after a merge of a pull request.
on:
    workflow_run:
        workflows: 
          - learn-github-actions
        types:
            - completed

jobs:
    semantic-release:
        name: Create Release
        runs-on: ubuntu-latest
    
        steps:
            - name: Clone repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Get next version
              id: get_next_version
              uses: thenativeweb/get-next-version@main  

            - name: Create new release
              if: ${{ steps.get_next_version.outputs.hasNextVersion == 'true' }}
              run: |
                NEXT_VERSION=${{ steps.get_next_version.outputs.version }}
                echo "Next version is $NEXT_VERSION"
                git tag $NEXT_VERSION
                git push origin $NEXT_VERSION
